### ISSUE TITLE
Knob_widget

### ISSUE THREAD

**Issue by prasanth0927** [alr2413/knob_widget#1]
We can't able to display the lable value in knob.Example,I have to set the knob value 0 to 100 (Min=0.0 , Max=100).It does't not divide into equal sessions (Example 0 , 20 ,40 ,60 ,80 ,100 ).Kindly clarify this issue

**Comment by alr2413** [comment]
That's because I only show the major thick labels. Check the `knob_tick_painter.dart` file to figure it out.
Right now, I don't have time to spend on it, maybe next week.... 
This is the main part painting labels:

```
for (int i = 0; i <= totalTickCount; i++) {
        bool isMajor = i % minorTickCount == 0;
        if (isMajor) {
          _textPainter.text = TextSpan(
            text: _getLabel((i * minorTickAngle).toInt()).toStringAsFixed(0),
            style: labelStyle,
          );
          _textPainter.layout(
            minWidth: 0,
            maxWidth: double.maxFinite,
          );
          canvas.rotate(-(i * rotationAngle + startAngle * pi / 180 - pi / 2));
          _textPainter.paint(
            canvas,
            Offset(
              -_textPainter.width / 2 +
                  labelRadius * sin(startAngle * pi / 180 - pi / 2),
              -_textPainter.height / 2 +
                  labelRadius * (1 - cos(startAngle * pi / 180 - pi / 2)),
            ),
          );
          canvas.rotate(i * rotationAngle + startAngle * pi / 180 - pi / 2);
        }
```

**Comment by prasanth0927** [comment]
Thanks for the information sir.But , I have one more question sir.In any
slider widget property we have a function like onChange : (value) {......}
. But here there is no onChange option sir.Kindly update it also sir....

**Comment by alr2413** [comment]
use controller for that purpose, check the example source code again and look for `_controller.addOnValueChangedListener(valueChangedListener);`

**Comment by alr2413** [comment]
added showing minor tick parameter to knob style.
